### ISSUE TITLE
Release first version

### ISSUE THREAD

**Issue by dbanty** [rigetti/qcs-sdk-rust#18]
# TODO
- [x] Get `quil-rust` updated with all pending features and released so this can use that version
- [x] Get OSS licenses approved (and remove Cargo Deny TODO)
- [x] Setup Semantic Release
- [x] Setup Cargo credentials for release
